#!/usr/bin/env bash
# shellcheck disable=SC1091
set -euo pipefail

# create symlinks for all dotfiles based on preset
# requires DOTFILES_DIR to be set

SCRIPT_DIR="${BASH_SOURCE%/*}"
DOTFILES_DIR="${DOTFILES_DIR:-$(cd "$(dirname "$(dirname "$SCRIPT_DIR")")" && pwd)}"
export DOTFILES_DIR

source "$SCRIPT_DIR/../_lib/common.sh"
source "$SCRIPT_DIR/../_lib/rollback.sh"
# create_link / copy_config / install_local (source order matters: common +
# rollback must load first)
source "$SCRIPT_DIR/../_lib/symlink.sh"

PRESET="${DOTFILES_PRESET:-full}"
FAILED=0


print_section "Creating symlinks"
echo "Source: $DOTFILES_DIR"
echo "Preset: $PRESET"
echo ""

# zsh (minimal)
# ~/.zshrc is a personal file that sources the dotfiles framework.
# two states: exists (leave it) or doesn't exist (create from template)
echo "Zsh configuration:"

if [[ -f "$HOME/.zshrc" ]]; then
  if grep -q "dotfiles.zsh" "$HOME/.zshrc" 2>/dev/null; then
    success "Personal ~/.zshrc exists (sources dotfiles framework)"
  else
    warn "$HOME/.zshrc exists but doesn't source dotfiles.zsh"
    info "Add this line to source the framework: source ~/dotfiles/zsh/dotfiles.zsh"
  fi
else
  # no .zshrc at all, create from template
  cp "$DOTFILES_DIR/zsh/zshrc.template" "$HOME/.zshrc"
  success "Created ~/.zshrc from template"
  printf '  %s→%s Edit with: nvim ~/.zshrc\n' "${CYAN}" "${NC}"
fi

# these are still symlinked (shared config, not personal)
create_link "$DOTFILES_DIR/zsh/zprofile" "$HOME/.zprofile"
# p10k.zsh: user-owned, generated by `p10k configure`; not managed by dotfiles

# user config files go to XDG location
ZSH_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
mkdir -p "$ZSH_CONFIG_DIR"

# tmux (minimal)
echo ""
echo "Tmux configuration:"
# note: .tmux.conf is generated by theme-switch to XDG location
# we'll create the compatibility symlink after theme generation (see below)
create_link "$DOTFILES_DIR/tmux" "$HOME/.tmux"

install_local "$DOTFILES_DIR/tmux/local.conf.template" "${XDG_CONFIG_HOME:-$HOME/.config}/tmux/local.conf"

# dotfiles CLI (minimal)
echo ""
echo "Dotfiles CLI:"
mkdir -p "$HOME/.local/bin"
create_link "$DOTFILES_DIR/scripts/dotfiles" "$HOME/.local/bin/dotfiles"

# formatters
echo ""
echo "Formatter configuration:"
create_link "$DOTFILES_DIR/formatters/prettierrc.json" "$HOME/.prettierrc"
create_link "$DOTFILES_DIR/formatters/editorconfig" "$HOME/.editorconfig"

# nvim (core)
# link only: packages come from the Brewfile core section via install-packages.
if should_install "core"; then
    echo ""
    echo "Neovim configuration:"
    create_link "$DOTFILES_DIR/nvim" "$HOME/.config/nvim"

    install_local "$DOTFILES_DIR/nvim/local.lua.template" "$HOME/.config/nvim/local.lua"

    # install .luarc.json (lua_ls workspace config) from the template. the
    # dotfiles repo root is lua_ls's workspace, so .luarc.json lives there.
    # kept machine-local (gitignored) so diagnostics can be tweaked per machine.
    # plugin and nvim runtime type libraries are supplied on demand by
    # lazydev.nvim, so there is no machine-specific path to substitute
    cp "$DOTFILES_DIR/.luarc.json.template" "$DOTFILES_DIR/.luarc.json"
    success "Installed $DOTFILES_DIR/.luarc.json (lua_ls workspace config)"

    # user spell dictionary (zg adds words here, repo dictionary has shared terms)
    user_spell_dir="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/spell"
    mkdir -p "$user_spell_dir"
    if [[ ! -f "$user_spell_dir/en.utf-8.add" ]]; then
        touch "$user_spell_dir/en.utf-8.add"
        success "Created user spell dictionary at $user_spell_dir/en.utf-8.add"
    fi
fi

# Hammerspoon (full)
if should_install "full"; then
    echo ""
    echo "Hammerspoon configuration:"
    mkdir -p "$HOME/.hammerspoon"
    create_link "$DOTFILES_DIR/hammerspoon/init.lua" "$HOME/.hammerspoon/init.lua"
    install_local "$DOTFILES_DIR/hammerspoon/local.lua.template" "$HOME/.hammerspoon/local.lua"
fi

# Ghostty (core)
# config is generated by theme-switch to XDG location (~/.config/ghostty/config)
# on macOS, symlink Application Support to XDG location
if should_install "core"; then
    echo ""
    echo "Ghostty configuration:"
    mkdir -p "$HOME/.config/ghostty"

    # note: Ghostty on macOS loads from BOTH ~/Library/Application Support/
    # and ~/.config/ghostty/. we only write to XDG, no symlink needed.
    # a symlink between them causes double-loading and config-file cycle errors

    install_local "$DOTFILES_DIR/ghostty/local.template" "$HOME/.config/ghostty/local"
fi

# Karabiner (full)
if should_install "full"; then
    echo ""
    echo "Karabiner configuration:"
    copy_config "$DOTFILES_DIR/karabiner/karabiner.json" "$HOME/.config/karabiner/karabiner.json"
fi

# gh-dash (core)
# config is generated by theme-switch to XDG location (~/.config/gh-dash/config.yml)
if should_install "core"; then
    echo ""
    echo "gh-dash configuration:"
    mkdir -p "$HOME/.config/gh-dash"

    install_local "$DOTFILES_DIR/gh-dash/local.yml.template" "$HOME/.config/gh-dash/local.yml"
    create_link "$DOTFILES_DIR/gh-dash/dash-repo-sync" "$HOME/.local/bin/dash-repo-sync"
fi

# btop (core)
if should_install "core"; then
    echo ""
    echo "btop configuration:"
    copy_config "$DOTFILES_DIR/btop/btop.conf" "$HOME/.config/btop/btop.conf"
fi

# yazi (core)
# per-file symlinks (not a whole-dir symlink) so theme-switch can write a
# generated theme.toml into ~/.config/yazi without it landing back in the repo
if should_install "core"; then
    echo ""
    echo "Yazi configuration:"
    # drop any legacy whole-dir symlink first so we own a real directory
    # (the 0.2.109 migration also handles this; this keeps it idempotent here)
    if [[ -L "$HOME/.config/yazi" ]]; then
        rm "$HOME/.config/yazi"
    fi
    mkdir -p "$HOME/.config/yazi"
    create_link "$DOTFILES_DIR/yazi/yazi.toml" "$HOME/.config/yazi/yazi.toml"
    create_link "$DOTFILES_DIR/yazi/keymap.toml" "$HOME/.config/yazi/keymap.toml"
fi
# launchers (core)
if should_install "core"; then
    echo ""
    echo "Launchers:"
    mkdir -p "$HOME/.local/launchers"
    create_link "$DOTFILES_DIR/launchers/dev" "$HOME/.local/launchers/dev"
fi

# LazyGit / LazyDocker (core)
# link only: packages come from the Brewfile core section
if should_install "core"; then
    echo ""
    echo "LazyGit configuration:"
    lazygit_dir="$HOME/.config/lazygit"
    mkdir -p "$lazygit_dir"

    create_link "$DOTFILES_DIR/lazygit/config.yml" "$lazygit_dir/config.yml"
    install_local "$DOTFILES_DIR/lazygit/local.yml.template" "$lazygit_dir/local.yml"

    echo ""
    echo "LazyDocker configuration:"
    # lazydocker: keep as copy-on-install (no include mechanism)
    if [[ "$(uname)" == "Darwin" ]]; then
        lazydocker_dir="$HOME/Library/Application Support/lazydocker"
    else
        lazydocker_dir="$HOME/.config/lazydocker"
    fi
    copy_config "$DOTFILES_DIR/lazydocker/config.yml" "$lazydocker_dir/config.yml"
    create_link "$DOTFILES_DIR/lazydocker/format-logs.awk" "$lazydocker_dir/format-logs.awk"
fi

# aerc (core)
# aerc.conf is shareable (symlinked); accounts.conf is user-owned (from template,
# holds real addresses) with secrets in the macOS keychain via *-cred-cmd
if should_install "core"; then
    echo ""
    echo "aerc configuration:"
    aerc_dir="$HOME/.config/aerc"
    mkdir -p "$aerc_dir"

    create_link "$DOTFILES_DIR/aerc/aerc.conf" "$aerc_dir/aerc.conf"
    create_link "$DOTFILES_DIR/aerc/binds.conf" "$aerc_dir/binds.conf"
    install_local "$DOTFILES_DIR/aerc/accounts.conf.template" "$aerc_dir/accounts.conf"
    # aerc refuses accounts.conf unless it is owner-only (600), else it drops to
    # the setup wizard on launch
    chmod 600 "$aerc_dir/accounts.conf"
fi

# ImageMagick font map (core, macOS only)
# homebrew's imagemagick ships empty type-*.xml stubs whose glyph paths resolve
# to nothing, so SVGs with text (image.nvim rendering shields.io badges) fail
# `identify` with "unable to read font". point real macOS system fonts at the
# cache. linux imagemagick has a working fontconfig cache, so skip it there
if should_install "core" && [[ "$(uname)" == "Darwin" ]]; then
    echo ""
    echo "ImageMagick font map:"
    create_link "$DOTFILES_DIR/imagemagick/type.xml" "${XDG_CONFIG_HOME:-$HOME/.config}/ImageMagick/type.xml"
fi

# statusline theme resolver (core): sourced by an AI CLI coding agent's
# statusline (Claude Code, Copilot CLI, Antigravity CLI) to colour it from the
# active dotfiles theme. see docs/THEME-SYSTEM.md
if should_install "core"; then
    echo ""
    echo "Statusline theme resolver:"
    create_link "$DOTFILES_DIR/scripts/_lib/statusline-theme.sh" "${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/statusline-theme.sh"
fi

# ─────────────────────────────────────────
# generate themed configurations
# ─────────────────────────────────────────
echo ""
info "Generating themed configurations"

if [[ -x "$DOTFILES_DIR/scripts/theme-switch" ]]; then
    # get current theme or default to dracula
    current_theme="dracula"
    theme_file="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/current-theme"

    if [[ -f "$theme_file" ]]; then
        current_theme=$(cat "$theme_file")
    fi

    info "Applying theme: $current_theme"
    "$DOTFILES_DIR/scripts/theme-switch" "$current_theme" --quiet || {
        warn "Failed to apply theme, using default (dracula)"
        "$DOTFILES_DIR/scripts/theme-switch" dracula --quiet
    }
    success "Generated themed configurations"
    
    # create compatibility symlink from ~/.tmux.conf to XDG location
    # (do this after theme-switch generates the file)
    echo ""
    info "Creating tmux compatibility symlink"
    xdg_tmux_conf="${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"
    if [[ -f "$xdg_tmux_conf" ]]; then
        create_link "$xdg_tmux_conf" "$HOME/.tmux.conf"
    else
        warn "XDG tmux config not found at $xdg_tmux_conf"
    fi
else
    warn "theme-switch script not found, skipping theme generation"
fi

echo ""

# record step completion
record_step "symlinks"

if [[ $FAILED -eq 0 ]]; then
    success "All symlinks created successfully!"
    exit 0
else
    error "Some symlinks failed to create. Check the output above."
    exit 1
fi
