#!/usr/bin/env bash
# shellcheck disable=SC1091
set -euo pipefail

# creates the symlinks, local override files and generated configs for a preset

SCRIPT_DIR="${BASH_SOURCE%/*}"
DOTFILES_DIR="${DOTFILES_DIR:-$(cd "$(dirname "$(dirname "$SCRIPT_DIR")")" && pwd)}"
export DOTFILES_DIR

source "$SCRIPT_DIR/../_lib/common.sh"
source "$SCRIPT_DIR/../_lib/rollback.sh"
# symlink.sh needs common.sh and rollback.sh loaded first
source "$SCRIPT_DIR/../_lib/symlink.sh"

PRESET="${DOTFILES_PRESET:-full}"
FAILED=0

print_section "Creating symlinks"
echo "Source: $DOTFILES_DIR"
echo "Preset: $PRESET"
echo ""

# zsh (minimal)
# ~/.zshrc is user-owned: created from the template when missing, otherwise left
echo "Zsh configuration:"

if [[ -f "$HOME/.zshrc" ]]; then
    if grep -q "dotfiles.zsh" "$HOME/.zshrc" 2>/dev/null; then
        success "Personal ~/.zshrc exists (sources dotfiles framework)"
    else
        warn "$HOME/.zshrc exists but doesn't source dotfiles.zsh"
        info "Add this line to source the framework: source ~/dotfiles/zsh/dotfiles.zsh"
    fi
else
    cp "$DOTFILES_DIR/zsh/zshrc.template" "$HOME/.zshrc"
    success "Created ~/.zshrc from template"
    printf '  %s→%s Edit with: nvim ~/.zshrc\n' "${CYAN}" "${NC}"
fi

create_link "$DOTFILES_DIR/zsh/zprofile" "$HOME/.zprofile"
# ~/.p10k.zsh is user-owned (generated by `p10k configure`) and not linked

ZSH_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
mkdir -p "$ZSH_CONFIG_DIR"

# tmux (minimal)
echo ""
echo "Tmux configuration:"
# theme-switch generates tmux.conf into the XDG location; ~/.tmux.conf is
# linked to it after theme generation below
create_link "$DOTFILES_DIR/tmux" "$HOME/.tmux"

install_local "$DOTFILES_DIR/tmux/local.conf.template" "${XDG_CONFIG_HOME:-$HOME/.config}/tmux/local.conf"

# dotfiles CLI (minimal)
echo ""
echo "Dotfiles CLI:"
mkdir -p "$HOME/.local/bin"
create_link "$DOTFILES_DIR/scripts/dotfiles" "$HOME/.local/bin/dotfiles"

# formatters
echo ""
echo "Formatter configuration:"
create_link "$DOTFILES_DIR/formatters/prettierrc.json" "$HOME/.prettierrc"
create_link "$DOTFILES_DIR/formatters/editorconfig" "$HOME/.editorconfig"

# nvim (core)
if should_install "core"; then
    echo ""
    echo "Neovim configuration:"
    create_link "$DOTFILES_DIR/nvim" "$HOME/.config/nvim"

    install_local "$DOTFILES_DIR/nvim/local.lua.template" "$HOME/.config/nvim/local.lua"

    # .luarc.json (lua_ls workspace config) lives at the repo root, which is
    # lua_ls's workspace. gitignored, and overwritten from the template each run
    cp "$DOTFILES_DIR/.luarc.json.template" "$DOTFILES_DIR/.luarc.json"
    success "Installed $DOTFILES_DIR/.luarc.json (lua_ls workspace config)"

    # user spell dictionary (zg adds words here, repo dictionary has shared terms)
    user_spell_dir="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/spell"
    mkdir -p "$user_spell_dir"
    if [[ ! -f "$user_spell_dir/en.utf-8.add" ]]; then
        touch "$user_spell_dir/en.utf-8.add"
        success "Created user spell dictionary at $user_spell_dir/en.utf-8.add"
    fi
fi

# hammerspoon (full)
if should_install "full"; then
    echo ""
    echo "Hammerspoon configuration:"
    mkdir -p "$HOME/.hammerspoon"
    create_link "$DOTFILES_DIR/hammerspoon/init.lua" "$HOME/.hammerspoon/init.lua"
    install_local "$DOTFILES_DIR/hammerspoon/local.lua.template" "$HOME/.hammerspoon/local.lua"
fi

# ghostty (core)
# config is generated by theme-switch to the XDG location (~/.config/ghostty/config)
if should_install "core"; then
    echo ""
    echo "Ghostty configuration:"
    mkdir -p "$HOME/.config/ghostty"

    # ghostty on macOS loads from both ~/Library/Application Support/ and
    # ~/.config/ghostty/. a symlink between them double-loads the config and
    # raises config-file cycle errors, so only the XDG path is written

    install_local "$DOTFILES_DIR/ghostty/local.template" "$HOME/.config/ghostty/local"
fi

# zed (core)
# keymap.json and tasks.json carry no per-machine values and zed writes through
# the symlink. settings.json mixes shared and per-machine prefs (font size,
# theme) and zed has no include mechanism, so it is copy-on-install
if should_install "core"; then
    echo ""
    echo "Zed configuration:"
    mkdir -p "$HOME/.config/zed"

    create_link "$DOTFILES_DIR/zed/keymap.json" "$HOME/.config/zed/keymap.json"
    create_link "$DOTFILES_DIR/zed/tasks.json" "$HOME/.config/zed/tasks.json"
    copy_config "$DOTFILES_DIR/zed/settings.json" "$HOME/.config/zed/settings.json"
fi

# karabiner (full)
if should_install "full"; then
    echo ""
    echo "Karabiner configuration:"
    copy_config "$DOTFILES_DIR/karabiner/karabiner.json" "$HOME/.config/karabiner/karabiner.json"
fi

# gh-dash (core)
# config is generated by theme-switch to the XDG location (~/.config/gh-dash/config.yml)
if should_install "core"; then
    echo ""
    echo "gh-dash configuration:"
    mkdir -p "$HOME/.config/gh-dash"

    install_local "$DOTFILES_DIR/gh-dash/local.yml.template" "$HOME/.config/gh-dash/local.yml"
    create_link "$DOTFILES_DIR/gh-dash/dash-repo-sync" "$HOME/.local/bin/dash-repo-sync"
fi

# btop (core)
if should_install "core"; then
    echo ""
    echo "btop configuration:"
    copy_config "$DOTFILES_DIR/btop/btop.conf" "$HOME/.config/btop/btop.conf"
fi

# yazi (core)
# linked per file: theme-switch writes a generated theme.toml into
# ~/.config/yazi, which must not be a symlink into the repo
if should_install "core"; then
    echo ""
    echo "Yazi configuration:"
    # a whole-dir symlink is replaced with a real directory
    if [[ -L "$HOME/.config/yazi" ]]; then
        rm "$HOME/.config/yazi"
    fi
    mkdir -p "$HOME/.config/yazi"
    create_link "$DOTFILES_DIR/yazi/yazi.toml" "$HOME/.config/yazi/yazi.toml"
    create_link "$DOTFILES_DIR/yazi/keymap.toml" "$HOME/.config/yazi/keymap.toml"
fi
# launchers (core)
if should_install "core"; then
    echo ""
    echo "Launchers:"
    mkdir -p "$HOME/.local/launchers"
    create_link "$DOTFILES_DIR/launchers/dev" "$HOME/.local/launchers/dev"
fi

# lazygit / lazydocker (core)
if should_install "core"; then
    echo ""
    echo "LazyGit configuration:"
    lazygit_dir="$HOME/.config/lazygit"
    mkdir -p "$lazygit_dir"

    create_link "$DOTFILES_DIR/lazygit/config.yml" "$lazygit_dir/config.yml"
    install_local "$DOTFILES_DIR/lazygit/local.yml.template" "$lazygit_dir/local.yml"

    echo ""
    echo "LazyDocker configuration:"
    # lazydocker has no include mechanism, so its config is copy-on-install
    if [[ "$(uname)" == "Darwin" ]]; then
        lazydocker_dir="$HOME/Library/Application Support/lazydocker"
    else
        lazydocker_dir="$HOME/.config/lazydocker"
    fi
    copy_config "$DOTFILES_DIR/lazydocker/config.yml" "$lazydocker_dir/config.yml"
    create_link "$DOTFILES_DIR/lazydocker/format-logs.awk" "$lazydocker_dir/format-logs.awk"
fi

# imagemagick font map (core, macOS only)
# homebrew's imagemagick ships empty type-*.xml stubs, so SVGs with text fail
# `identify` with "unable to read font". linux uses its fontconfig cache
if should_install "core" && [[ "$(uname)" == "Darwin" ]]; then
    echo ""
    echo "ImageMagick font map:"
    create_link "$DOTFILES_DIR/imagemagick/type.xml" "${XDG_CONFIG_HOME:-$HOME/.config}/ImageMagick/type.xml"
fi

# statusline theme resolver (core), see docs/THEME-SYSTEM.md
if should_install "core"; then
    echo ""
    echo "Statusline theme resolver:"
    create_link "$DOTFILES_DIR/scripts/_lib/statusline-theme.sh" "${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/statusline-theme.sh"
fi

# ─────────────────────────────────────────
# generate themed configurations
# ─────────────────────────────────────────
echo ""
info "Generating themed configurations"

if [[ -x "$DOTFILES_DIR/scripts/theme-switch" ]]; then
    current_theme="dracula"
    theme_file="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/current-theme"

    if [[ -f "$theme_file" ]]; then
        current_theme=$(cat "$theme_file")
    fi

    info "Applying theme: $current_theme"
    "$DOTFILES_DIR/scripts/theme-switch" "$current_theme" --quiet || {
        warn "Failed to apply theme, using default (dracula)"
        "$DOTFILES_DIR/scripts/theme-switch" dracula --quiet
    }
    success "Generated themed configurations"

    echo ""
    info "Creating tmux compatibility symlink"
    xdg_tmux_conf="${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"
    if [[ -f "$xdg_tmux_conf" ]]; then
        create_link "$xdg_tmux_conf" "$HOME/.tmux.conf"
    else
        warn "XDG tmux config not found at $xdg_tmux_conf"
    fi
else
    warn "theme-switch script not found, skipping theme generation"
fi

echo ""

record_step "symlinks"

if [[ $FAILED -eq 0 ]]; then
    success "All symlinks created successfully!"
    exit 0
else
    error "Some symlinks failed to create. Check the output above."
    exit 1
fi
