#!/usr/bin/env bash
# shellcheck disable=SC1091
set -euo pipefail

# Create symlinks for all dotfiles based on preset
# Requires DOTFILES_DIR to be set

SCRIPT_DIR="${BASH_SOURCE%/*}"
DOTFILES_DIR="${DOTFILES_DIR:-$(cd "$(dirname "$(dirname "$SCRIPT_DIR")")" && pwd)}"
export DOTFILES_DIR

source "$SCRIPT_DIR/../_lib/common.sh"
source "$SCRIPT_DIR/../_lib/rollback.sh"

PRESET="${DOTFILES_PRESET:-full}"
FAILED=0

create_link() {
    local source="$1"
    local dest="$2"

    # Validate source exists before creating symlink
    if [[ ! -e "$source" && ! -L "$source" ]]; then
        printf "${RED}FAILED:${NC} Source not found: %s\n" "$source"
        FAILED=1
        return 1
    fi

    # Ensure parent directory exists
    mkdir -p "$(dirname "$dest")"

    # Remove existing symlink if present
    if [[ -L "$dest" ]]; then
        rm "$dest"
    fi

    # If destination exists and is not a symlink, back it up inline
    if [[ -e "$dest" ]]; then
        local backup_base="$HOME/.dotfiles-backup"
        local backup_dir
        backup_dir="$backup_base/inline-$(date +%Y%m%d-%H%M%S)-$$"
        mkdir -p "$backup_base"
        chmod 700 "$backup_base"
        mkdir -p "$backup_dir"
        chmod 700 "$backup_dir"

        local relative_path="${dest#"$HOME"/}"
        local backup_path="$backup_dir/$relative_path"
        mkdir -p "$(dirname "$backup_path")"

        mv "$dest" "$backup_path"
        printf "${YELLOW}Backed up:${NC} %s -> %s\n" "$dest" "$backup_path"
    fi

    # Create symlink
    if ln -sf "$source" "$dest"; then
        printf "${GREEN}Created:${NC} %s -> %s\n" "$dest" "$source"
        # Record for rollback
        record_symlink "$dest" "$source"
        return 0
    else
        printf "${RED}FAILED:${NC} Could not create symlink %s\n" "$dest"
        FAILED=1
        return 1
    fi
}

# Copy config file from repo to destination (copy-on-install pattern).
# If destination already exists, keeps it untouched (user-owned).
copy_config() {
    local source="$1"
    local dest="$2"

    # Ensure parent directory exists
    mkdir -p "$(dirname "$dest")"

    if [[ ! -e "$dest" ]]; then
        cp "$source" "$dest"
        success "Created $dest from dotfiles"
        printf '  %s→%s Edit with: nvim %s\n' "${CYAN}" "${NC}" "$dest"
    else
        info "Kept existing $dest"
    fi
}

# Install a local override file from template (never overwrite user customisations).
install_local() {
    local template="$1"
    local dest="$2"

    mkdir -p "$(dirname "$dest")"
    if [[ ! -f "$dest" ]]; then
        cp "$template" "$dest"
        success "Created $dest from template"
        printf '  %s→%s Edit with: nvim %s\n' "${CYAN}" "${NC}" "$dest"
    else
        info "Kept existing $dest"
    fi
}


print_section "Creating symlinks"
echo "Source: $DOTFILES_DIR"
echo "Preset: $PRESET"
echo ""

# Zsh (minimal)
# ~/.zshrc is a personal file that sources the dotfiles framework.
# Two states: exists (leave it) or doesn't exist (create from template).
echo "Zsh configuration:"

if [[ -f "$HOME/.zshrc" ]]; then
  if grep -q "dotfiles.zsh" "$HOME/.zshrc" 2>/dev/null; then
    success "Personal ~/.zshrc exists (sources dotfiles framework)"
  else
    warn "$HOME/.zshrc exists but doesn't source dotfiles.zsh"
    info "Add this line to source the framework: source ~/dotfiles/zsh/dotfiles.zsh"
  fi
else
  # No .zshrc at all — create from template
  cp "$DOTFILES_DIR/zsh/zshrc.template" "$HOME/.zshrc"
  success "Created ~/.zshrc from template"
  printf '  %s→%s Edit with: nvim ~/.zshrc\n' "${CYAN}" "${NC}"
fi

# These are still symlinked (shared config, not personal)
create_link "$DOTFILES_DIR/zsh/zprofile" "$HOME/.zprofile"
# p10k.zsh: user-owned, generated by `p10k configure` — not managed by dotfiles

# User config files go to XDG location
ZSH_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
mkdir -p "$ZSH_CONFIG_DIR"

# Tmux (minimal)
echo ""
echo "Tmux configuration:"
# Note: .tmux.conf is generated by theme-switch to XDG location
# We'll create the compatibility symlink after theme generation (see below)
create_link "$DOTFILES_DIR/tmux" "$HOME/.tmux"

install_local "$DOTFILES_DIR/tmux/local.conf.template" "${XDG_CONFIG_HOME:-$HOME/.config}/tmux/local.conf"

# Dotfiles CLI (minimal)
echo ""
echo "Dotfiles CLI:"
mkdir -p "$HOME/.local/bin"
create_link "$DOTFILES_DIR/scripts/dotfiles" "$HOME/.local/bin/dotfiles"

# Formatters
echo ""
echo "Formatter configuration:"
create_link "$DOTFILES_DIR/formatters/prettierrc.json" "$HOME/.prettierrc"
create_link "$DOTFILES_DIR/formatters/editorconfig" "$HOME/.editorconfig"

# Neovim (core)
if should_install "core"; then
    echo ""
    echo "Neovim configuration:"
    create_link "$DOTFILES_DIR/nvim" "$HOME/.config/nvim"

    install_local "$DOTFILES_DIR/nvim/local.lua.template" "$HOME/.config/nvim/local.lua"

    # Install .luarc.json (lua_ls workspace config) from the template. The
    # dotfiles repo root is lua_ls's workspace, so .luarc.json lives there.
    # Kept machine-local (gitignored) so diagnostics can be tweaked per machine.
    # Plugin and Neovim runtime type libraries are supplied on demand by
    # lazydev.nvim, so there is no machine-specific path to substitute.
    cp "$DOTFILES_DIR/.luarc.json.template" "$DOTFILES_DIR/.luarc.json"
    success "Installed $DOTFILES_DIR/.luarc.json (lua_ls workspace config)"

    # User spell dictionary (zg adds words here, repo dictionary has shared terms)
    user_spell_dir="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/spell"
    mkdir -p "$user_spell_dir"
    if [[ ! -f "$user_spell_dir/en.utf-8.add" ]]; then
        touch "$user_spell_dir/en.utf-8.add"
        success "Created user spell dictionary at $user_spell_dir/en.utf-8.add"
    fi
fi

# Hammerspoon (full)
if should_install "full"; then
    echo ""
    echo "Hammerspoon configuration:"
    mkdir -p "$HOME/.hammerspoon"
    create_link "$DOTFILES_DIR/hammerspoon/init.lua" "$HOME/.hammerspoon/init.lua"
    install_local "$DOTFILES_DIR/hammerspoon/local.lua.template" "$HOME/.hammerspoon/local.lua"
fi

# Ghostty (core)
# Config is generated by theme-switch to XDG location (~/.config/ghostty/config)
# On macOS, symlink Application Support to XDG location
if should_install "core"; then
    echo ""
    echo "Ghostty configuration:"
    mkdir -p "$HOME/.config/ghostty"

    # Note: Ghostty on macOS loads from BOTH ~/Library/Application Support/
    # and ~/.config/ghostty/. We only write to XDG — no symlink needed.
    # A symlink between them causes double-loading and config-file cycle errors.

    install_local "$DOTFILES_DIR/ghostty/local.template" "$HOME/.config/ghostty/local"
fi

# Karabiner (full)
if should_install "full"; then
    echo ""
    echo "Karabiner configuration:"
    copy_config "$DOTFILES_DIR/karabiner/karabiner.json" "$HOME/.config/karabiner/karabiner.json"
fi

# gh-dash (core)
# Config is generated by theme-switch to XDG location (~/.config/gh-dash/config.yml)
if should_install "core"; then
    echo ""
    echo "gh-dash configuration:"
    mkdir -p "$HOME/.config/gh-dash"

    install_local "$DOTFILES_DIR/gh-dash/local.yml.template" "$HOME/.config/gh-dash/local.yml"
    create_link "$DOTFILES_DIR/gh-dash/dash-repo-sync" "$HOME/.local/bin/dash-repo-sync"
fi

# btop (core)
if should_install "core"; then
    echo ""
    echo "btop configuration:"
    copy_config "$DOTFILES_DIR/btop/btop.conf" "$HOME/.config/btop/btop.conf"
fi
# Launchers (core)
if should_install "core"; then
    echo ""
    echo "Launchers:"
    mkdir -p "$HOME/.local/launchers"
    create_link "$DOTFILES_DIR/launchers/dev" "$HOME/.local/launchers/dev"
fi

# LazyGit / LazyDocker (core)
if should_install "core"; then
    echo ""
    echo "LazyGit configuration:"
    # Use ~/.config/lazygit/ on all platforms (LG_CONFIG_FILE overrides the default path)
    lazygit_dir="$HOME/.config/lazygit"
    mkdir -p "$lazygit_dir"

    create_link "$DOTFILES_DIR/lazygit/config.yml" "$lazygit_dir/config.yml"
    install_local "$DOTFILES_DIR/lazygit/local.yml.template" "$lazygit_dir/local.yml"

    # Lazydocker: keep as copy-on-install (no include mechanism)
    if [[ "$(uname)" == "Darwin" ]]; then
        lazydocker_dir="$HOME/Library/Application Support/lazydocker"
    else
        lazydocker_dir="$HOME/.config/lazydocker"
    fi
    copy_config "$DOTFILES_DIR/lazydocker/config.yml" "$lazydocker_dir/config.yml"
    create_link "$DOTFILES_DIR/lazydocker/format-logs.awk" "$lazydocker_dir/format-logs.awk"
fi

# Statusline theme resolver (core) — sourced by an AI CLI coding agent's
# statusline (Claude Code, Copilot CLI, Antigravity CLI) to colour it from the
# active dotfiles theme. See docs/THEME-SYSTEM.md.
if should_install "core"; then
    echo ""
    echo "Statusline theme resolver:"
    create_link "$DOTFILES_DIR/scripts/_lib/statusline-theme.sh" "${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/statusline-theme.sh"
fi

# ─────────────────────────────────────────
# Generate themed configurations
# ─────────────────────────────────────────
echo ""
info "Generating themed configurations"

if [[ -x "$DOTFILES_DIR/scripts/theme-switch" ]]; then
    # Get current theme or default to dracula
    current_theme="dracula"
    theme_file="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/current-theme"

    if [[ -f "$theme_file" ]]; then
        current_theme=$(cat "$theme_file")
    fi

    info "Applying theme: $current_theme"
    "$DOTFILES_DIR/scripts/theme-switch" "$current_theme" --quiet || {
        warn "Failed to apply theme, using default (dracula)"
        "$DOTFILES_DIR/scripts/theme-switch" dracula --quiet
    }
    success "Generated themed configurations"
    
    # Create compatibility symlink from ~/.tmux.conf to XDG location
    # (do this after theme-switch generates the file)
    echo ""
    info "Creating tmux compatibility symlink"
    xdg_tmux_conf="${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"
    if [[ -f "$xdg_tmux_conf" ]]; then
        create_link "$xdg_tmux_conf" "$HOME/.tmux.conf"
    else
        warn "XDG tmux config not found at $xdg_tmux_conf"
    fi
else
    warn "theme-switch script not found, skipping theme generation"
fi

echo ""

# Record step completion
record_step "symlinks"

if [[ $FAILED -eq 0 ]]; then
    success "All symlinks created successfully!"
    exit 0
else
    error "Some symlinks failed to create. Check the output above."
    exit 1
fi
